update=Вс 17 фев 2019 08:03:37
version=1
last_client=kicad
[pcbnew]
version=1
LastNetListRead=
UseCmpFile=1
PadDrill=0.600000000000
PadDrillOvalY=0.600000000000
PadSizeH=1.500000000000
PadSizeV=1.500000000000
PcbTextSizeV=1.500000000000
PcbTextSizeH=1.500000000000
PcbTextThickness=0.300000000000
ModuleTextSizeV=1.000000000000
ModuleTextSizeH=1.000000000000
ModuleTextSizeThickness=0.150000000000
SolderMaskClearance=0.000000000000
SolderMaskMinWidth=0.000000000000
DrawSegmentWidth=0.200000000000
BoardOutlineThickness=0.100000000000
ModuleOutlineThickness=0.150000000000
[cvpcb]
version=1
NetIExt=net
[general]
version=1
[eeschema]
version=1
LibDir=../../../../../usr/share/kicad/modules
[eeschema/libraries]
LibName1=power
LibName2=device
LibName3=transistors
LibName4=conn
LibName5=linear
LibName6=regul
LibName7=74xx
LibName8=cmos4000
LibName9=adc-dac
LibName10=memory
LibName11=xilinx
LibName12=microcontrollers
LibName13=dsp
LibName14=microchip
LibName15=analog_switches
LibName16=motorola
LibName17=texas
LibName18=intel
LibName19=audio
LibName20=interface
LibName21=digital-audio
LibName22=philips
LibName23=display
LibName24=cypress
LibName25=siliconi
LibName26=opto
LibName27=atmel
LibName28=contrib
LibName29=valves
LibName30=/home/vmv/kicad chems/kicad-library/library/ac-dc
LibName31=/home/vmv/kicad chems/kicad-library/library/adc-dac
LibName32=/home/vmv/kicad chems/kicad-library/library/Altera
LibName33=/home/vmv/kicad chems/kicad-library/library/analog_devices
LibName34=/home/vmv/kicad chems/kicad-library/library/analog_switches
LibName35=/home/vmv/kicad chems/kicad-library/library/atmel
LibName36=/home/vmv/kicad chems/kicad-library/library/audio
LibName37=/home/vmv/kicad chems/kicad-library/library/Battery_Management
LibName38=/home/vmv/kicad chems/kicad-library/library/bbd
LibName39=/home/vmv/kicad chems/kicad-library/library/Bosch
LibName40=/home/vmv/kicad chems/kicad-library/library/brooktre
LibName41=/home/vmv/kicad chems/kicad-library/library/Connector
LibName42=/home/vmv/kicad chems/kicad-library/library/contrib
LibName43=/home/vmv/kicad chems/kicad-library/library/cypress
LibName44=/home/vmv/kicad chems/kicad-library/library/dc-dc
LibName45=/home/vmv/kicad chems/kicad-library/library/Decawave
LibName46=/home/vmv/kicad chems/kicad-library/library/device
LibName47=/home/vmv/kicad chems/kicad-library/library/digital-audio
LibName48=/home/vmv/kicad chems/kicad-library/library/Diode
LibName49=/home/vmv/kicad chems/kicad-library/library/Display
LibName50=/home/vmv/kicad chems/kicad-library/library/driver_gate
LibName51=/home/vmv/kicad chems/kicad-library/library/dsp
LibName52=/home/vmv/kicad chems/kicad-library/library/DSP_Microchip_DSPIC33
LibName53=/home/vmv/kicad chems/kicad-library/library/elec-unifil
LibName54=/home/vmv/kicad chems/kicad-library/library/ESD_Protection
LibName55=/home/vmv/kicad chems/kicad-library/library/Espressif
LibName56=/home/vmv/kicad chems/kicad-library/library/FPGA_Actel
LibName57=/home/vmv/kicad chems/kicad-library/library/ftdi
LibName58=/home/vmv/kicad chems/kicad-library/library/gennum
LibName59=/home/vmv/kicad chems/kicad-library/library/Graphic
LibName60=/home/vmv/kicad chems/kicad-library/library/hc11
LibName61=/home/vmv/kicad chems/kicad-library/library/infineon
LibName62=/home/vmv/kicad chems/kicad-library/library/intel
LibName63=/home/vmv/kicad chems/kicad-library/library/interface
LibName64=/home/vmv/kicad chems/kicad-library/library/intersil
LibName65=/home/vmv/kicad chems/kicad-library/library/ir
LibName66=/home/vmv/kicad chems/kicad-library/library/Lattice
LibName67=/home/vmv/kicad chems/kicad-library/library/LED
LibName68=/home/vmv/kicad chems/kicad-library/library/LEM
LibName69=/home/vmv/kicad chems/kicad-library/library/linear
LibName70=/home/vmv/kicad chems/kicad-library/library/Logic_74xgxx
LibName71=/home/vmv/kicad chems/kicad-library/library/Logic_74xx
LibName72=/home/vmv/kicad chems/kicad-library/library/Logic_CMOS_4000
LibName73=/home/vmv/kicad chems/kicad-library/library/Logic_CMOS_IEEE
LibName74=/home/vmv/kicad chems/kicad-library/library/logic_programmable
LibName75=/home/vmv/kicad chems/kicad-library/library/Logic_TTL_IEEE
LibName76=/home/vmv/kicad chems/kicad-library/library/maxim
LibName77=/home/vmv/kicad chems/kicad-library/library/MCU_Microchip_PIC10
LibName78=/home/vmv/kicad chems/kicad-library/library/MCU_Microchip_PIC12
LibName79=/home/vmv/kicad chems/kicad-library/library/MCU_Microchip_PIC16
LibName80=/home/vmv/kicad chems/kicad-library/library/MCU_Microchip_PIC18
LibName81=/home/vmv/kicad chems/kicad-library/library/MCU_Microchip_PIC24
LibName82=/home/vmv/kicad chems/kicad-library/library/MCU_Microchip_PIC32
LibName83=/home/vmv/kicad chems/kicad-library/library/MCU_NXP_Kinetis
LibName84=/home/vmv/kicad chems/kicad-library/library/MCU_NXP_LPC
LibName85=/home/vmv/kicad chems/kicad-library/library/MCU_NXP_S08
LibName86=/home/vmv/kicad chems/kicad-library/library/MCU_Parallax
LibName87=/home/vmv/kicad chems/kicad-library/library/MCU_ST_STM8
LibName88=/home/vmv/kicad chems/kicad-library/library/MCU_ST_STM32
LibName89=/home/vmv/kicad chems/kicad-library/library/MCU_Texas_MSP430
LibName90=/home/vmv/kicad chems/kicad-library/library/Mechanical
LibName91=/home/vmv/kicad chems/kicad-library/library/memory
LibName92=/home/vmv/kicad chems/kicad-library/library/microchip
LibName93=/home/vmv/kicad chems/kicad-library/library/microcontrollers
LibName94=/home/vmv/kicad chems/kicad-library/library/modules
LibName95=/home/vmv/kicad chems/kicad-library/library/Motor
LibName96=/home/vmv/kicad chems/kicad-library/library/motor_drivers
LibName97=/home/vmv/kicad chems/kicad-library/library/motorola
LibName98=/home/vmv/kicad chems/kicad-library/library/nordicsemi
LibName99=/home/vmv/kicad chems/kicad-library/library/nxp
LibName100=/home/vmv/kicad chems/kicad-library/library/onsemi
LibName101=/home/vmv/kicad chems/kicad-library/library/opto
LibName102=/home/vmv/kicad chems/kicad-library/library/Oscillators
LibName103=/home/vmv/kicad chems/kicad-library/library/philips
LibName104=/home/vmv/kicad chems/kicad-library/library/power
LibName105=/home/vmv/kicad chems/kicad-library/library/powerint
LibName106=/home/vmv/kicad chems/kicad-library/library/Power_Management
LibName107=/home/vmv/kicad chems/kicad-library/library/pspice
LibName108=/home/vmv/kicad chems/kicad-library/library/references
LibName109=/home/vmv/kicad chems/kicad-library/library/regul
LibName110=/home/vmv/kicad chems/kicad-library/library/Relay
LibName111=/home/vmv/kicad chems/kicad-library/library/RF_Bluetooth
LibName112=/home/vmv/kicad chems/kicad-library/library/rfcom
LibName113=/home/vmv/kicad chems/kicad-library/library/RFSolutions
LibName114=/home/vmv/kicad chems/kicad-library/library/Sensor_Current
LibName115=/home/vmv/kicad chems/kicad-library/library/Sensor_Humidity
LibName116=/home/vmv/kicad chems/kicad-library/library/sensors
LibName117=/home/vmv/kicad chems/kicad-library/library/silabs
LibName118=/home/vmv/kicad chems/kicad-library/library/siliconi
LibName119=/home/vmv/kicad chems/kicad-library/library/supertex
LibName120=/home/vmv/kicad chems/kicad-library/library/Switch
LibName121=/home/vmv/kicad chems/kicad-library/library/texas
LibName122=/home/vmv/kicad chems/kicad-library/library/Transformer
LibName123=/home/vmv/kicad chems/kicad-library/library/Transistor
LibName124=/home/vmv/kicad chems/kicad-library/library/triac_thyristor
LibName125=/home/vmv/kicad chems/kicad-library/library/Valve
LibName126=/home/vmv/kicad chems/kicad-library/library/video
LibName127=/home/vmv/kicad chems/kicad-library/library/wiznet
LibName128=/home/vmv/kicad chems/kicad-library/library/Worldsemi
LibName129=/home/vmv/kicad chems/kicad-library/library/Xicor
LibName130=/home/vmv/kicad chems/kicad-library/library/xilinx
LibName131=/home/vmv/kicad chems/kicad-library/library/xilinx-artix7
LibName132=/home/vmv/kicad chems/kicad-library/library/xilinx-kintex7
LibName133=/home/vmv/kicad chems/kicad-library/library/xilinx-spartan6
LibName134=/home/vmv/kicad chems/kicad-library/library/xilinx-virtex5
LibName135=/home/vmv/kicad chems/kicad-library/library/xilinx-virtex6
LibName136=/home/vmv/kicad chems/kicad-library/library/xilinx-virtex7
LibName137=/home/vmv/kicad chems/kicad-library/library/zetex
LibName138=/home/vmv/kicad chems/kicad-library/library/Zilog
